@startuml inline_umlgraph_1.png
class Matrix {
-n : int
-tab : int**
+Matrix()
+Matrix(int n, int* t)
+Matrix(Matrix& m)
+~Matrix()
+alokuj(int n) : Matrix&
+losuj() : Matrix&
+odwroc() : Matrix&
+wstaw(int x, int y, int wartosc) : Matrix&
+pokaz(int x, int y) : int

}
@enduml
